:white_check_mark: Validate Docker Compose installation
- Add check to ensure Docker Compose is installed
- Abort workflow if Docker Compose installation fails

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -28,12 +28,16 @@ jobs:
           sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
           sudo chmod +x /usr/local/bin/docker-compose
           sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
+          if ! command -v docker-compose; then
+            echo "Docker Compose installation failed"
+            exit 1
+          fi
 
       - name: Set up Docker Compose
         env:
           JDBC_DATABASE_USERNAME: ${{ secrets.JDBC_DATABASE_USERNAME }}
           JDBC_DATABASE_PASSWORD: ${{ secrets.JDBC_DATABASE_PASSWORD }}
-        run: docker-compose -f ./compose.yaml up -d
+        run: docker-compose -f compose.yaml up -d
 
       - uses: actions/checkout@v4
 
